[project]
name = "prediction-interval-comp-ii-house-price"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "autogluon>=1.3.1",
    "ipykernel>=6.29.5",
    "pandas>=2.2.3",
]
